# Generated by Django 4.2.13 on 2024-06-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listings_delete_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
    ]
